[build]
command = "npm run build"
publish = "out"

[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"

[[plugins]]
package = "netlify-plugin-cypress"

  [plugins.inputs.preBuild]
  enable = false
  record = true
  start = 'npm run dev'
  wait-on = 'http://localhost:3000'
  wait-on-timeout = '30'
  group = "test"
  tag = "development build"

  [plugins.inputs.postBuild]
  enable = false
  record = true
  group = "staging"
  tag = "production build"

  [plugins.inputs]
  enable = true
  record = true
  group = "live"
  tag = "production build"

[[plugins]]
package = "@netlify/plugin-nextjs"