[build]
command = "npm run build"
publish = "out"

[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"
CYPRESS_RECORD_KEY = "CYPRESS_RECORD_KEY"

[[plugins]]
package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
  enable = true
  record = true
  group = "production build"
  tag = "production"

[[plugins]]
package = "@netlify/plugin-nextjs"