[build]
command = "npm run build"
publish = "out"

[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"

[[plugins]]
package = "netlify-plugin-cypress"

  [plugins.inputs.preBuild]
  enable = true
  record = true
  group = "development build"
  tag = "development"
  start = 'npm run dev'
  wait-on = 'http://localhost:3000'
  wait-on-timeout = '30'


  [plugins.inputs.postBuild]
  enable = false
  record = true
  group = "production build"
  tag = "production"

[[plugins]]
package = "@netlify/plugin-nextjs"